steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.6
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python Version: 3.6'
  
- script: |
    python -m pip install --upgrade pip
    pip install databricks-cli
  displayName: 'Setup Agent'